### PR TITLE
added typescript types to react-bulma-components

### PR DESCRIPTION
**Pull request by dfee**

### CODE REVIEW

**Comment by sc14aec** [comment]
Just a question on this - what happens if you define a custom colour using sass? The `Color` type is limited to the predefined ones, could this be a string instead? Or is there a way to add additional values?

**Comment by dfee** [comment]
Right now there's no way to add additional values. I'm not sure how the interface would be to do such a thing without just making it `string`... the autocomplete for the default colors is very helpful.

I wonder if there's a way in TS to allow for a string literal default but allow a user to supply additional string values?

**Comment by couds** [comment]
@sc14aec @dfee About the color issue, maybe we can change the proptype to by 
```
color: PropType.oneOfType([
  PropType.oneOf(COLOR_ARRAY),
  PropType.string,
])
```

but I don't know how that will work on ts.

what do you think?

**Comment by RonaldDijks** [comment]
That ts doesn't give good type hinting when you merge the color and string types is expected behaviour.  The color type is a subset of string so when merging color and string you get... string. There's no way to get around this at the moment afaik

**Comment by couds** [comment]
Closes #61

**Comment by dukedave** [comment]
I'm getting:
```
TypeScript error: Could not find a declaration file for module 'react-bulma-components'. '/Users/dave/dev/trrah/react-app/node_modules/react-bulma-components/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-bulma-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-bulma-components';`  TS7016

    4 |
    5 | import 'react-bulma-components/dist/react-bulma-components.min.css';
  > 6 | import { Button } from 'react-bulma-components';
```

---

@dfee should I be able to do this?

```
$ npm install @types/react-bulma-components
```

Because it gives me:
```
$ npm install @types/react-bulma-components
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-bulma-components - Not found
npm ERR! 404
npm ERR! 404  '@types/react-bulma-components@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by couds** [comment]
Hi @dukedave which version of the library are you using? (if you are on the latest of next there is currentñy a know bug in v3.0.1-4 you can see the details here https://github.com/couds/react-bulma-components/issues/165

**Comment by dukedave** [comment]
Aha, so @couds I *was* on `2.3.0` (where I observed the error), but then I learned of 'next' and so I tried:

```
npm install react-bulma-components@next
``` 

This got me 3.0.1-4 which resolves the issue 🎉

**Comment by Defite** [comment]
Wellm there is still no support for TS, as I see. I tried to export some form components and compiler exits with:

```
Could not find a declaration file for module 'react-bulma-components/lib/components/form'.
```

**Comment by arnaud-deprez** [comment]
Hi @Defite,

Replace your import `import Form from 'react-bulma-components/lib/components/form'` to `import { Form } from 'react-bulma-components'` and this should work as long as you are using latest `react-bulma-components@next`

**Pull request merged**
