### PR TITLE
Add pagination first last pages (documentation)

### PR DESCRIPTION
**Pull request by ykyuen**
As suggested in https://github.com/couds/react-bulma-components/pull/283.

### CODE REVIEW

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
Just a minor nitpick, can you remove the space between the curly braces for consistency? LGTM otherwise!

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
ahhh sorry, forgot to mention that string props should look like `prop="string"` without the braces. also that was quick!

**Review by MrCreeper1008 — CHANGES_REQUESTED** [review]
I think you forgot to remove the right curly braces after the double quotes :)

**Comment by ykyuen** [comment]
Sorry for the stupid mistake. I shouldn't commit before bed. :joy:

Thanks for your help on the review process. :bow:

**Review by MrCreeper1008 — APPROVED** [review]
looks good!

**Pull request merged**
