### PR TITLE
Change default import to use advanced configuration by default

### PR DESCRIPTION
**Pull request by couds**
I created this PR as a discussion. I will let this PR open for a week or two and will merge it depending on what the community says.

The mail idea its to remove some boilerplate for using the advance configuration. so will be left like this

```jsx
import { Button } from 'react-bulma-component' // For advance configuration
import { Button } from 'react-bulma-component/dist' // For Basic configuration
``` 

@MrCreeper1008 some thoughts?

### CODE REVIEW

**Comment by couds** [comment]
Fix #132

**Comment by MrCreeper1008** [comment]
@couds Is tree-shaking supported for both methods of importing components?

**Comment by MrCreeper1008** [comment]
I have been wondering if it's possible to merge basic/advanced configurations together because it's a bit confusing imo, but I have no idea where to start.

**Comment by couds** [comment]
This will be done probably on another branch after some cleanup, closing it

**Pull request closed without merging**
