### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by MrCreeper1008**
This will be a PR tracking the development of the documentation. Dropping CRA in favor of Docusaurus 2.  

cc @couds @Quadrisheriff  

## Installation
- [x] Basic
- [x] Advanced (next.js, CRA, gatsby, etc.)

## Components:
- [ ] Box
- [ ] Breadcrumb
- [ ] Button
- [ ] Card
- [ ] Column
- [ ] Container
- [ ] Content
- [ ] Dropdown
- [ ] Footer
- [ ] Form
- [ ] Heading
- [ ] Hero 
- [ ] Icon 
- [ ] Image
- [ ] Level
- [ ] List
- [ ] Loader
- [ ] Media
- [ ] Message
- [ ] Menu
- [ ] Modal
- [ ] Navbar
- [ ] Notification
- [ ] Pagination
- [ ] Panel
- [ ] Progress
- [ ] Section
- [ ] Tabs
- [ ] Table
- [ ] Tag
- [ ] Tile

### CODE REVIEW

**Comment by MrCreeper1008** [comment]
`docs` branch deleted.

**Comment by timorthi** [comment]
Hey @MrCreeper1008 , I was looking to contribute to this branch but noticed that it's based off of `master` rather than `next`. Since `next` (v4) is filled with major changes, shouldn't we shift our focus to documenting the `next` branch instead?

**Comment by MrCreeper1008** [comment]
This PR is open before development of v4.0 starts which is why it's based on `master`. The documentation is in a separate root folder, so when `next` merges into `master`, it shouldn't be a huge issue. You can document the new stuff here. Thank you!

**Comment by MrCreeper1008** [comment]
@couds there's a docs storybook addon that integrates documentation right inside storybook 👀 how do you think?

**Comment by couds** [comment]
@MrCreeper1008 can you pass me the link to check it out?

**Comment by MrCreeper1008** [comment]
@couds https://storybook.js.org/docs/react/writing-docs/introduction

**Comment by MrCreeper1008** [comment]
Merging this into next since the new docs depends on `v4`.

**Pull request merged**
