### PR TITLE
List items containing custom children will now be styled correctly

### LINKED ISSUE #169: Menu List Item - hover active state does not work if using elements
I have a component like this.

```
      <Menu
        className="share-admin-menu"
        style={{
          backgroundColor: 'white',
          padding: '20px',
          color: 'white',
          width: '200px',
        }}
      >
        <Menu.List title={username} className="share-admin-menu__title">
          <Menu.List.Item
            active={active === 'edit'}
            onClick={this.onEditClick}>
              <div className="share-admin-menu__edit-container mb-one">
                <p className="share-admin-menu__text-option">
                  Edit
                </p>
                <Icon
                  className="debut-icon debut-icon--pointer ml-one"
                  icon="IconPencil"
                  color="#518DCA"
                />
              </div>
          </Menu.List.Item>
          <Menu.List.Item
            active={active === 'delete'}
            onClick={this.onDeleteClick}>
              <div className="share-admin-menu__delete-container mb-one">
                <p className="share-admin-menu__text-option">Delete</p>
                <Icon
                  className="debut-icon debut-icon--pointer ml-one"
                  icon="IconTrash"
                  color="#EA1D64"
                />
              </div>
            </Menu.List.Item>
          <Menu.List.Item
            active={active === 'detail'}
            onClick={this.onFollowersClick}>
            <div className="share-admin-menu__go-to-container">
              <p className="share-admin-menu__text-option">Go to Share</p>
              <Icon
                className="debut-icon debut-icon--pointer ml-one"
                icon="IconGo"
                color="#3ac569"
              />
            </div>
          </Menu.List.Item>
        </Menu.List>
      </Menu>
```

which renders out this...

Screenshot of Opera (3-19-19, 12-10-57 PM)

Visually it looks good but i lose the ability of the hover and active state.  Is there a work around for this?

### PR DESCRIPTION
**Pull request by MrCreeper1008**
Content inside `list-item` must be wrapped with an `<a>` anchor or the list item will not be styled correctly.  

Closes #169

### CODE REVIEW

**Comment by MrCreeper1008** [comment]
I don't see adding an anchor tag may break custom behaviors except some minor styling issues though. Can you elaborate a bit? Thanks.

**Comment by couds** [comment]
Hi @MrCreeper1008 you are right I missundertood what you wanted to do. What do you think about changing the code to this instead

```javascript
const MenuListItem = ({
  children,
  active,
  className,
  domRef: ref,
  ...props
}) => {
  if (
    typeof children !== 'string'
    && React.Children.toArray(children).length === 1
    && React.Children.only(children).type === List
  ) {
    const child = React.Children.only(children);
    return (
      <li ref={ref}>
        <Element className={classnames(className, { 'is-active': active })} {...props}>
          {child.props.title}
        </Element>
        {React.cloneElement(child, { title: undefined })}
      </li>
    );
  }

  return (
    <li ref={ref}>
      <Element className={classnames(className, { 'is-active': active })} {...props}>
        {children}
      </Element>
    </li>
  );
};
```

This way we also allow to pass more than one children to the Item like

```
<Menu.List.Item>
  <Icon icon="payment" /> Payments
</Menu.List.Item>
```

**Comment by MrCreeper1008** [comment]
Looks great except, imo, the.`.only` in the third expression is not necessary and I'd change it to directly point at the first element of the array returned from `.toArray`. Would be faster this way correct?

**Comment by couds** [comment]
to do that we will need to add the toArray call before the render (to be able to use it for check the lenght and get the first element,, and that will add a probably unnecesary check on every render.

**Comment by MrCreeper1008** [comment]
Yea you're right I misread the code.

**Comment by MrCreeper1008** [comment]
What happened to Travis????

**Comment by MrCreeper1008** [comment]
@couds all tests should be run successfully, but I'm not sure why travis got stuck. Pretty sure that lead to the decrease in coverage.

**Pull request merged**
